*&---------------------------------------------------------------------*
*& Report  ZBD00_RFC_BPC_DATA_COPY
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*

REPORT  ZBD00_RFC_BPC_DATA_COPY.

TYPE-POOLS: ABAP.

DATA: LV_APPL_ID        TYPE UJA_APPL-APPLICATION_ID ,
      LT_APPL_ID        TYPE STANDARD TABLE OF UJA_APPL-APPLICATION_ID ,
      LV_MEMEBER        TYPE UJ_DIM_MEMBER ,
      LT_SEL            TYPE UJ0_T_SEL ,
      LS_SEL            TYPE UJ0_S_SEL ,
      LV_PC             TYPE N LENGTH 2 ,
      LV_NAME           TYPE C LENGTH 7 .

FIELD-SYMBOLS: <FS_DATA>        TYPE ANY ,
               <FT_DATA>        TYPE ANY TABLE .

SELECTION-SCREEN BEGIN OF BLOCK APP WITH FRAME TITLE TEXT-001.
PARAMETERS: P_APPSET TYPE UJA_APPL-APPSET_ID OBLIGATORY VALUE CHECK VISIBLE LENGTH 18 .
SELECT-OPTIONS: S_APPLS FOR LV_APPL_ID OBLIGATORY NO INTERVALS.
SELECTION-SCREEN END OF BLOCK APP.

SELECTION-SCREEN BEGIN OF BLOCK SEL WITH FRAME TITLE TEXT-002.
*line 1
SELECTION-SCREEN BEGIN OF LINE .
PARAMETERS: P_D01 TYPE UJA_DIM_APPL-DIMENSION .
SELECT-OPTIONS: S_D01 FOR LV_MEMEBER .
SELECTION-SCREEN END OF LINE .
*line 2
  SELECTION-SCREEN BEGIN OF LINE .
    PARAMETERS: P_D02 TYPE UJA_DIM_APPL-DIMENSION .
    SELECT-OPTIONS: S_D02 FOR LV_MEMEBER .
  SELECTION-SCREEN END OF LINE .
*line 3
  SELECTION-SCREEN BEGIN OF LINE .
    PARAMETERS: P_D03 TYPE UJA_DIM_APPL-DIMENSION .
    SELECT-OPTIONS: S_D03 FOR LV_MEMEBER .
  SELECTION-SCREEN END OF LINE .
*line 4
SELECTION-SCREEN BEGIN OF LINE .
  PARAMETERS: P_D04 TYPE UJA_DIM_APPL-DIMENSION .
  SELECT-OPTIONS: S_D04 FOR LV_MEMEBER .
SELECTION-SCREEN END OF LINE .
*line 5
  SELECTION-SCREEN BEGIN OF LINE .
    PARAMETERS: P_D05 TYPE UJA_DIM_APPL-DIMENSION .
    SELECT-OPTIONS: S_D05 FOR LV_MEMEBER .
  SELECTION-SCREEN END OF LINE .
SELECTION-SCREEN END OF BLOCK SEL.

*at selection-screen

START-OF-SELECTION.

BREAK-POINT.

* get selections from selection-screen
DO.
ADD 1 TO LV_PC.
CLEAR LV_NAME.
CONCATENATE `p_d` LV_PC INTO LV_NAME.
ASSIGN (LV_NAME) TO <FS_DATA>.
  IF <FS_DATA> IS NOT ASSIGNED OR <FS_DATA> IS INITIAL .
    EXIT.
  ENDIF.

LS_SEL-DIMENSION = <FS_DATA>.
CLEAR LV_NAME.
CONCATENATE `s_d` LV_PC `[]` INTO LV_NAME.
ASSIGN (LV_NAME) TO <FT_DATA>.
  IF <FT_DATA> IS NOT ASSIGNED OR <FT_DATA> IS INITIAL .
    CONTINUE.
  ENDIF.

LOOP AT <FT_DATA> ASSIGNING <FS_DATA>.
MOVE-CORRESPONDING <FS_DATA> TO LS_SEL.
COLLECT LS_SEL INTO LT_SEL .
ENDLOOP.
ENDDO.
BREAK-POINT.


* clear

* write
