method IF_RSPC_MAINTAIN~MAINTAIN.
  CALL METHOD SET_PC_TYPE.

  CALL METHOD CL_UJD_CUSTOM_TYPE=>IF_RSPC_MAINTAIN~MAINTAIN
  EXPORTING
    I_VARIANT      = I_VARIANT
    I_T_CHAIN      = I_T_CHAIN
    I_DISPLAY_ONLY = I_DISPLAY_ONLY
  IMPORTING
    E_VARIANT      = E_VARIANT
    E_VARIANT_TEXT = E_VARIANT_TEXT.
endmethod.
