method IF_RSPC_GET_VARIANT~GET_VARIANT.
  CALL METHOD CL_UJD_CUSTOM_TYPE=>IF_RSPC_GET_VARIANT~GET_VARIANT
  EXPORTING
    I_TYPE         = I_TYPE
    I_VARIANT      = I_VARIANT
    I_T_CHAIN      = I_T_CHAIN
    I_T_SELECT     = I_T_SELECT
    I_OBJVERS      = I_OBJVERS
  IMPORTING
    E_VARIANT      = E_VARIANT
    E_VARIANT_TEXT = E_VARIANT_TEXT.
endmethod.
