method IF_RSPC_MAINTAIN~GET_HEADER.
  CALL METHOD SET_PC_TYPE.

  CALL METHOD CL_UJD_CUSTOM_TYPE=>IF_RSPC_MAINTAIN~GET_HEADER
  EXPORTING
    I_VARIANT      = I_VARIANT
    I_OBJVERS      = I_OBJVERS
  IMPORTING
    E_VARIANT_TEXT = E_VARIANT_TEXT
    E_S_CHANGED    = E_S_CHANGED
    E_CONTREL      = E_CONTREL
    E_CONTTIMESTMP = E_CONTTIMESTMP.
endmethod.
