method CONSTRUCTOR.
CALL METHOD SUPER->CONSTRUCTOR
EXPORTING
PREVIOUS = PREVIOUS
.
me->I_APPSET_ID = I_APPSET_ID .
me->I_APPL_ID = I_APPL_ID .
me->I_INFOPROVIDE = I_INFOPROVIDE .
me->I_DIM_NAME = I_DIM_NAME .
clear me->textid.
if textid is initial.
  IF_T100_MESSAGE~T100KEY = ZCX_BD00_CREATE_OBJ .
else.
  IF_T100_MESSAGE~T100KEY = TEXTID.
endif.
endmethod.
