method CONSTRUCTOR.
CALL METHOD SUPER->CONSTRUCTOR
EXPORTING
PREVIOUS = PREVIOUS
.
me->LINE = LINE .
me->OFFSET = OFFSET .
me->TOKEN = TOKEN .
me->APPSET_ID = APPSET_ID .
me->APPL_ID = APPL_ID .
me->EXPECTED = EXPECTED .
me->INDEX = INDEX .
me->DIMENSION = DIMENSION .
me->ATTRIBUTE = ATTRIBUTE .
me->TABLENAME = TABLENAME .
me->CURSOR = CURSOR .
me->TOKEN1 = TOKEN1 .
clear me->textid.
if textid is initial.
  IF_T100_MESSAGE~T100KEY = ZCX_BDNL_SYNTAX_ERROR .
else.
  IF_T100_MESSAGE~T100KEY = TEXTID.
endif.
endmethod.
