*&---------------------------------------------------------------------*
*& Report  ZBDNL_TEST_CURSOR
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*

REPORT  ZBDNL_TEST_CURSOR.

DATA
: GR_O__PARSER TYPE REF TO ZCL_BDNL_PARSER
, LD_T__VARIABLE  TYPE ZBNLT_T__VARIABLE
, LD_S__VARIABLE  TYPE ZBNLT_S__VARIABLE
.

BREAK-POINT.

LD_S__VARIABLE-VAR = `$UYEAR$`.
LD_S__VARIABLE-VAL = `2015`.
INSERT LD_S__VARIABLE INTO TABLE LD_T__VARIABLE.

LD_S__VARIABLE-VAR = `$USCENARIO$`.
LD_S__VARIABLE-VAL = `PLAN`.
INSERT LD_S__VARIABLE INTO TABLE LD_T__VARIABLE.

LD_S__VARIABLE-VAR = `$SCENARIO_SET$`.
LD_S__VARIABLE-VAL = `PLAN`.
INSERT LD_S__VARIABLE INTO TABLE LD_T__VARIABLE.

LD_S__VARIABLE-VAR = `$TIME_SET$`.
LD_S__VARIABLE-VAL = `2014.JAN`.
INSERT LD_S__VARIABLE INTO TABLE LD_T__VARIABLE.

LD_S__VARIABLE-VAR = `$UFORMAT$`.
LD_S__VARIABLE-VAL = `ТС Пятерочка`.
INSERT LD_S__VARIABLE INTO TABLE LD_T__VARIABLE.




CREATE OBJECT GR_O__PARSER
  EXPORTING
    I_V__APPSET      = `DEMO`
    I_V__APPLICATION = `DEMO_01`
    I_V__FILENAME    = `NEW_LOGIC.LGF`
    I_T__VARIABLE    = LD_T__VARIABLE.

BREAK-POINT.

GR_O__PARSER->GET_STACK( ).
