method IF_RSPC_TRANSPORT~GET_TLOGO.

  CALL METHOD SET_PC_TYPE.

  CALL METHOD CL_UJD_CUSTOM_TYPE=>IF_RSPC_TRANSPORT~GET_TLOGO
    EXPORTING
      I_VARIANT = I_VARIANT
      I_OBJVERS = I_OBJVERS
    IMPORTING
      E_TLOGO   = E_TLOGO
      E_OBJNM   = E_OBJNM.

endmethod.
