*&---------------------------------------------------------------------*
*& Report  ZCHECK_SCRIPT
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*

REPORT  ZCHECK_SCRIPT.

TABLES
: UJA_APPSET_INFO
, UJA_APPL
.


SELECTION-SCREEN BEGIN OF BLOCK B1.
PARAMETERS: APPS TYPE UJA_APPSET_INFO-APPSET_ID   MODIF ID A00.
PARAMETERS: APPL TYPE UJA_APPL-APPLICATION_ID     MODIF ID A00.
PARAMETERS: SCLO TYPE UJA_APPL-APPLICATION_ID             MODIF ID A00 MEMORY ID QWE     .
SELECTION-SCREEN END OF BLOCK B1.

DATA
: LD_V__APPSET_ID         TYPE UJ_APPSET_ID
, LD_V__APPL_ID           TYPE UJ_APPL_ID
, LR_O__PARSER            TYPE REF TO ZCL_BDNL_PARSER
, LD_T__VARIABLE          TYPE  ZBNLT_T__VARIABLE
, LO_I_CONTEXT            TYPE REF TO IF_UJ_CONTEXT
, LD_S__USER              TYPE UJ0_S_USER
, LR_X__BDNL_PARSER       TYPE REF TO ZCX_BDNL_PARSER
, LD_S__ERROR             TYPE STRING
, LD_V__SCLO              TYPE UJ_DOCNAME
.


START-OF-SELECTION.
  LD_V__APPSET_ID = APPS.
  LD_V__APPL_ID   = APPL.
  LD_V__SCLO = SCLO.


  CALL METHOD CL_UJ_CONTEXT=>SET_CUR_CONTEXT
    EXPORTING
      I_APPSET_ID = LD_V__APPSET_ID
      IS_USER     = LD_S__USER
      I_APPL_ID   = LD_V__APPL_ID.

  LO_I_CONTEXT = CL_UJ_CONTEXT=>GET_CUR_CONTEXT( ).
  LO_I_CONTEXT->SWITCH_TO_SRVADMIN( ).


  CALL METHOD ZCL_BD00_CONTEXT=>SET_CONTEXT
    EXPORTING
      I_APPSET_ID = LD_V__APPSET_ID
      I_APPL_ID   = LD_V__APPL_ID
      I_S__USER   = LO_I_CONTEXT->DS_USER.

  CALL METHOD ZCL_BDNL_CONTAINER=>SET_CURRENT_SCRIPT
    EXPORTING
      APPSET_ID = LD_V__APPSET_ID
      APPL_ID   = LD_V__APPL_ID
      SCRIPT    = LD_V__SCLO.

  CREATE OBJECT LR_O__PARSER
    EXPORTING
      I_V__APPSET      = LD_V__APPSET_ID
      I_V__APPLICATION = LD_V__APPL_ID
      I_V__FILENAME    = LD_V__SCLO
      I_T__VARIABLE    = LD_T__VARIABLE.

  TRY.

      LR_O__PARSER->GET_STACK( ).

      WRITE: `Error not found` COLOR COL_POSITIVE.

    CATCH ZCX_BDNL_PARSER INTO LR_X__BDNL_PARSER.

      LOOP AT LR_X__BDNL_PARSER->ERRORTAB
           INTO LD_S__ERROR.

        WRITE / LD_S__ERROR COLOR COL_NEGATIVE.

      ENDLOOP.
  ENDTRY.

END-OF-SELECTION.
